import test from "node:test";import assert from "node:assert/strict";import {validateCandle,validateQuote} from "../src/market-data/schema.js";import {assessFreshness,detectCandleGap,assessQuote,dataQualityGate} from "../src/market-data/quality.js";import {createSource} from "../src/market-data/source.js";import {snapshotAsOf} from "../src/market-data/replay.js";
const candle={source:"binance",symbol:"BTCUSDT",interval:"1m",openTime:1000,closeTime:1999,open:100,high:110,low:90,close:105,volume:12};
test("valid candle and quote pass schema",()=>{assert.doesNotThrow(()=>validateCandle(candle));assert.doesNotThrow(()=>validateQuote({source:"binance",symbol:"BTCUSDT",bid:100,ask:101,observedAt:10000}));});
test("invalid OHLC and crossed quote are rejected",()=>{assert.throws(()=>validateCandle({...candle,high:80}));assert.throws(()=>validateQuote({source:"x",symbol:"BTC",bid:101,ask:100,observedAt:1}));});
test("freshness detects stale data",()=>{assert.equal(assessFreshness(9900,10000,200).fresh,true);assert.equal(assessFreshness(9000,10000,200).fresh,false);});
test("candle gap is detected",()=>{assert.equal(detectCandleGap({openTime:1000},{openTime:2000},1000),false);assert.equal(detectCandleGap({openTime:1000},{openTime:3000},1000),true);});
test("quality gate stops stale, gaps and untrusted data",()=>{assert.equal(dataQualityGate({freshness:{fresh:true}}).allowed,true);assert.equal(dataQualityGate({freshness:{fresh:false}}).allowed,false);assert.equal(dataQualityGate({freshness:{fresh:true},gap:true}).allowed,false);assert.equal(dataQualityGate({freshness:{fresh:true},sourceTrusted:false}).allowed,false);});
test("source trust is explicit",()=>{assert.equal(createSource({id:"binance",kind:"official"}).trustScore,1);assert.equal(createSource({id:"mystery",kind:"unknown"}).trustScore,0);});
test("as-of snapshot is deterministic",()=>{const r=[{observedAt:30,value:3},{observedAt:10,value:1},{observedAt:20,value:2}];assert.deepEqual(snapshotAsOf(r,25),{observedAt:20,value:2});assert.equal(snapshotAsOf(r,5),null);});
