import test from "node:test";import assert from "node:assert/strict";
import {runResearchCouncil,commonModeCouncil} from "../src/intelligence/multi-agent.js";
import {orderBookFeatures,microstructureSignal} from "../src/intelligence/microstructure.js";
import {derivativesFeatures,derivativesSignal} from "../src/intelligence/derivatives.js";
import {crossAssetRegime} from "../src/intelligence/cross-asset.js";
import {normalizeExternalEvidence,externalEvidenceAllowed} from "../src/intelligence/alternative-data.js";
import {constrainedOptimize,optimizationRequiresRevalidation} from "../src/intelligence/optimization.js";
import {inputCoverage,requireRepresentativeness} from "../src/intelligence/input-coverage.js";
import {brierScore,calibrationBins} from "../src/intelligence/calibration.js";
import {dueForRevalidation,revalidationDecision} from "../src/intelligence/revalidation.js";
import {buildResearchTrace,verifyResearchTrace} from "../src/intelligence/trace.js";
test("multi-agent council exposes dissent and waits on severe disagreement",()=>{const r=runResearchCouncil({evidence:{technical:[{score:90}],macro:[{score:40}],derivatives:[{score:85}],risk:[{score:88}]}});assert.equal(r.uncertainty,"high");assert.equal(r.decision,"WAIT");});
test("common mode detects correlated direction",()=>assert.equal(commonModeCouncil([{direction:"BUY"},{direction:"BUY"},{direction:"BUY"},{direction:"SELL"}]).commonModeRisk,true));
test("microstructure and derivatives produce bounded signals",()=>{const f=orderBookFeatures({bids:[{qty:100}],asks:[{qty:40}],trades:[{side:"BUY",qty:30},{side:"SELL",qty:5}]});assert.equal(microstructureSignal(f),"BUY_BIAS");const d=derivativesFeatures({fundingRate:.02,openInterestChange:.1});assert.equal(derivativesSignal(d),"CROWDED_LONG");});
test("cross asset and external evidence are freshness aware",()=>{assert.equal(crossAssetRegime({BTC:.02,ETH:.01}).regime,"RISK_ON");const e=normalizeExternalEvidence({source:"news",type:"sentiment",value:.8,timestamp:1000,now:2000,maxAgeMs:2000});assert.equal(externalEvidenceAllowed(e),true);});
test("optimization is constrained and changes require revalidation",()=>{assert.equal(constrainedOptimize([{expectedReturn:.2,leverage:1,drawdown:.1},{expectedReturn:.5,leverage:3,drawdown:.1}],{maxLeverage:2}).length,1);assert.equal(optimizationRequiresRevalidation({a:1},{a:2}),true);});
test("AI input coverage fails closed",()=>{const r=inputCoverage({required:["technical","macro"],provided:["technical"]});assert.equal(r.representative,false);assert.throws(()=>requireRepresentativeness(r),/coverage/);});
test("calibration metrics are deterministic",()=>{assert.equal(brierScore([{probability:.8,outcome:1},{probability:.2,outcome:0}]),.04);assert.equal(calibrationBins([{probability:.8,outcome:1}],10)[8].subset,1);});
test("revalidation expires and research traces are reconstructable",()=>{assert.equal(dueForRevalidation({lastValidatedAt:0,intervalMs:10,now:11}),true);assert.equal(revalidationDecision({valid:true,drift:true}).allowed,false);const t=buildResearchTrace({requestId:"r1",sources:["s"],agents:["technical"],decision:"WAIT"});assert.equal(verifyResearchTrace(t),true);});
