const CONTRACT_VERSION="1.0.0";const ExecutionTier=Object.freeze({PAPER:"paper",SHADOW:"shadow",LIMITED_LIVE:"limited-live",LIVE:"live"});
// Shared boundary normalization: one vocabulary for symbols and sides across
// contracts, execution, risk and reconciliation (case/whitespace insensitive).
function normalizeSymbol(v){return String(v??"").trim().toUpperCase();}
function normalizeSide(v){return String(v??"").trim().toUpperCase();}
function nonEmpty(v,n){if(typeof v!=="string"||v.trim()==="")throw new TypeError(n+" must be a non-empty string");}
function validateStrategySignal(s){if(!s||typeof s!=="object")throw new TypeError("signal must be an object");nonEmpty(s.strategyId,"strategyId");nonEmpty(s.strategyVersion,"strategyVersion");nonEmpty(s.symbol,"symbol");if(!["long","short","flat"].includes(s.direction))throw new TypeError("invalid direction");if(!Number.isFinite(s.opportunityScore)||s.opportunityScore<0||s.opportunityScore>100)throw new TypeError("opportunityScore must be 0..100");if(s.probability!==undefined&&(!Number.isFinite(s.probability)||s.probability<0||s.probability>1))throw new TypeError("probability must be 0..1");return true;}
function validateThesis(t){if(!t||typeof t!=="object")throw new TypeError("thesis must be an object");nonEmpty(t.thesisId,"thesisId");nonEmpty(t.statement,"statement");nonEmpty(t.invalidation,"invalidation");if(!Array.isArray(t.evidence)||t.evidence.length===0)throw new TypeError("evidence is required");return true;}
function validateRiskConfig(c){if(!c||typeof c!=="object")throw new TypeError("risk config must be an object");for(const k of ["maxPositionNotional","maxDailyLoss","maxDrawdown"])if(!Number.isFinite(c[k])||c[k]<=0)throw new TypeError(k+" must be positive");nonEmpty(c.version,"version");nonEmpty(c.configHash,"configHash");return true;}
function validatePortfolioState(s){if(!s||typeof s!=="object")throw new TypeError("portfolio state must be an object");if(!Number.isFinite(s.equity)||s.equity<0)throw new TypeError("equity must be non-negative");if(!Number.isFinite(s.dailyPnl)||!Number.isFinite(s.drawdown))throw new TypeError("portfolio metrics must be finite");return true;}
function validateOrder(o){if(!o||typeof o!=="object")throw new TypeError("order must be an object");nonEmpty(o.orderId,"orderId");nonEmpty(o.symbol,"symbol");if(!["BUY","SELL"].includes(normalizeSide(o.side)))throw new TypeError("invalid side");if(!Number.isFinite(o.quantity)||o.quantity<=0)throw new TypeError("quantity must be positive");if(!Object.values(ExecutionTier).includes(o.tier))throw new TypeError("invalid execution tier");return true;}
// Reconciliation status crosswalk: the contract vocabulary ("matched" |
// "mismatch" | "unknown") and the execution/reconciliation vocabulary
// ("RECONCILED" | "UNRESOLVED" | "MISMATCH") describe the same states. Only a
// matched/reconciled result passes; everything else blocks execution.
function validateReconciliation(r){if(!r||typeof r!=="object")throw new TypeError("reconciliation result must be an object");const status=typeof r.status==="string"?r.status.trim():r.status;if(!["matched","mismatch","unknown","RECONCILED","UNRESOLVED","MISMATCH"].includes(status))throw new TypeError("invalid reconciliation status");if(status!=="matched"&&status!=="RECONCILED")throw new Error("non-matched reconciliation blocks execution");return true;}
export {CONTRACT_VERSION,ExecutionTier,normalizeSymbol,normalizeSide,validateStrategySignal,validateThesis,validateRiskConfig,validatePortfolioState,validateOrder,validateReconciliation};
